Added templates
 - config file template
 - init file template
 - view template
 - html template
 - setup file template
 - run server template

These files get parsed and replaced

diff --git a/flarchitect b/flarchitect
--- a/flarchitect
+++ b/flarchitect
@@ -1,21 +1,43 @@
 #!/bin/bash
+
+function usage(){
+	echo -e "\nUsage: 
+	create [PROJECT_NAME],
+	create-view [PROJECT_NAME] [VIEW_NAME],
+	create-template [PROJECT_NAME] [TEMPLATE_NAME],
+	create-env [PROJECT_NAME],
+	del-env [PROJECT_NAME],
+	reset-env [PROJECT_NAME],
+	run-debug [PROJECT_NAME],
+	banner\n"
+}
+
+function run_debug_server(){
+	chmod +x "$1/bin/run_server"
+	./"$1/bin/run_server"
+}
+
 function create_project(){
 	PROJECT_NAME=$1
 
 	if [[ -d "$PROJECT_NAME" ]]; then
-		echo
-		echo "Project $PROJECT_NAME already exists."
-		echo
+		echo -e "\nProject $PROJECT_NAME already exists.\n"
 		exit 1
 	fi
 
 	if ! [[ -d "$PROJECT_NAME" ]]; then
 		mkdir "$PROJECT_NAME"
+		mkdir "$PROJECT_NAME/bin"
+		touch "$PROJECT_NAME/bin/run_server"
+		python3 flarchitects/flarchitects.py "bin" "$PROJECT_NAME"
 		touch "$PROJECT_NAME/setup.py"
+		python3 flarchitects/flarchitects.py "setup" "$PROJECT_NAME"
 		mkdir "$PROJECT_NAME/$PROJECT_NAME"
 		mkdir "$PROJECT_NAME/$PROJECT_NAME/bin"
 		touch "$PROJECT_NAME/$PROJECT_NAME/__init__.py"
+		python3 flarchitects/flarchitects.py "init" "$PROJECT_NAME"
 		touch "$PROJECT_NAME/$PROJECT_NAME/config.py"
+		python3 flarchitects/flarchitects.py "config" "$PROJECT_NAME"
 		mkdir "$PROJECT_NAME/$PROJECT_NAME/authorization"
 		touch "$PROJECT_NAME/$PROJECT_NAME/authorization/__init__.py"
 		mkdir "$PROJECT_NAME/$PROJECT_NAME/css"
@@ -27,13 +49,17 @@ function create_project(){
 		mkdir "$PROJECT_NAME/$PROJECT_NAME/static/images"
 		mkdir "$PROJECT_NAME/$PROJECT_NAME/static/js"
 		mkdir "$PROJECT_NAME/$PROJECT_NAME/templates"
+		touch "$PROJECT_NAME/$PROJECT_NAME/templates/hello_world.html"
+		python3 flarchitects/flarchitects.py "template" "$PROJECT_NAME" "hello_world"
 		mkdir "$PROJECT_NAME/$PROJECT_NAME/views"
-		touch "$PROJECT_NAME/$PROJECT_NAME/views/__init__.py"
-		echo
-		echo "Setup flask project architecture for $PROJECT_NAME."
+		INIT_FILE="$PROJECT_NAME/$PROJECT_NAME/views/__init__.py"
+		touch "$INIT_FILE"
+		python3 flarchitects/flarchitects.py "view" "$PROJECT_NAME" "hello_world"
+		echo "from $PROJECT_NAME.views.hello_world import *" >> "$INIT_FILE"
+		echo -e "\nSetup flask project architecture for $PROJECT_NAME."
 		if [[ -x "$(command -v tree)" ]]; then
 			tree "$PROJECT_NAME"
-			echo
+			echo -e "\n"
 		fi
 	fi
 }
@@ -45,34 +71,34 @@ function create_env(){
 	pip install --upgrade pip
 	pip install flask
 	cd ../
-	echo
-	echo "Created new environment in project '$1'."
-	echo
+	echo -e "\nCreated new environment in project '$1'.\n"
+}
+
+function install_app(){
+	cd $1
+	pip install -e .
+	cd ../
+	echo -e "\nCreated and installed project $1.\n"
 }
 
 case "$1" in
 	"create")
 		if [[ -z "$2" ]]; then
-			echo
-			echo "Usage: create [PROJECT_NAME]"
-			echo
+			usage
 			exit 1
 		fi
 		create_project "$2"
+		install_app "$2"
 		;;
 
 	"create-view")
 		if [[ -z "$2" ]] || [[ -z "$3" ]]; then
-			echo
-			echo "Usage: create-view [PROJECT_NAME] [VIEW_NAME]"
-			echo
+			usage
 			exit 1
 		fi
 		PROJECT_NAME=$2
 		if ! [[ -d "$PROJECT_NAME" ]]; then
-			echo
-			echo "Unable to locate project $PROJECT_NAME."
-			echo
+			echo -e "\nUnable to locate project $PROJECT_NAME.\n"
 			exit 1
 		fi
 		VIEW_NAME=$3
@@ -80,43 +106,33 @@ case "$1" in
 		INIT="$PROJECT_NAME/$PROJECT_NAME/views/__init__.py"
 		touch $NEWFILE
 		echo "from $PROJECT_NAME.views.$VIEW_NAME import *" >> $INIT
-		echo
-		echo "Created view $VIEW_NAME..."
-		echo
+		echo -e "\nCreated view $VIEW_NAME...\n"
+		python3 flarchitects/flarchitects.py "view" "$PROJECT_NAME" "$VIEW_NAME"
 		;;
 
 	"create-template")
 		if [[ -z $2 ]] || [[ -z $3 ]]; then
-			echo
-			echo "Usage: create-template [PROJECT_NAME] [TEMPLATE_NAME]"
-			echo
+			usage
 			exit 1
 		fi
 		PROJECT_NAME=$2
 		if ! [[ -d "$PROJECT_NAME" ]]; then
-			echo
-			echo "Unable to locate project $PROJECT_NAME."
-			echo
+			echo -e "\nUnable to locate project $PROJECT_NAME.\n"
 			exit 1
 		fi
 		TEMPLATE_NAME=$3
 		touch "$PROJECT_NAME/$PROJECT_NAME/templates/$TEMPLATE_NAME.html"
-		echo "Created template $TEMPLATE_NAME..."
-		echo
+		echo -e "Created template $TEMPLATE_NAME...\n"
 		;;
 
 	"create-env")
 		if [[ -z $2 ]]; then
-			echo
-			echo "Usage: create-env [PROJECT_NAME]"
-			echo
+			usage
 			exit 1
 		fi
 		PROJECT_NAME=$2
 		if ! [[ -d "$PROJECT_NAME" ]]; then
-			echo
-			echo "Unable to locate project $PROJECT_NAME."
-			echo
+			echo -e "\nUnable to locate project $PROJECT_NAME.\n"
 			exit 1
 		fi
 		if [[ -d "$PROJECT_NAME/env" ]]; then
@@ -132,34 +148,30 @@ case "$1" in
 
 	"del-env")
 		if [[ -z $2 ]]; then
-			echo "Usage: del-env [PROJECT_NAME]"
+			usage
 			exit 1
 		fi
 		PROJECT_NAME=$2
 		if ! [[ -d "$PROJECT_NAME" ]]; then
-			echo "Unable to locate project $PROJECT_NAME."
+			echo -e "\nUnable to locate project $PROJECT_NAME.\n"
 			exit 1
 		fi
 		if ! [[ -d "$PROJECT_NAME/env" ]]; then
-			echo
-			echo "No existing environment to delete in project '$PROJECT_NAME'."
-			echo
+			echo -e "\nNo existing environment to delete in project '$PROJECT_NAME'.\n"
 			exit 1
 		fi
 		rm -rf "$PROJECT_NAME/env"
-		echo
-		echo "Deleted environment from project $PROJECT_NAME."
-		echo
+		echo -e "\nDeleted environment from project $PROJECT_NAME.\n"
 		;;
 
 	"reset-env")
 		if [[ -z $2 ]]; then
-			echo "Usage: reset-env [PROJECT_NAME]"
+			usage
 			exit 1
 		fi
 		PROJECT_NAME=$2
 		if ! [[ -d "$PROJECT_NAME" ]]; then
-			echo "Unable to locate project $PROJECT_NAME."
+			echo -e "\nUnable to locate project $PROJECT_NAME.\n"
 			exit 1
 		fi
 		if [[ -d "$PROJECT_NAME/env" ]]; then
@@ -168,8 +180,17 @@ case "$1" in
 		create_env $PROJECT_NAME
 		;;
 
+	"run-debug")
+		if [[ -z $2 ]]; then
+			usage
+			exit 1
+		fi
+		PROJECT_NAME=$2
+		run_debug_server $PROJECT_NAME
+		;;
+
 	"help")
-		echo
+		echo -e "\n"
 		echo "************************************************************************************"
 		echo "The Flarchitect framework aims to provide easy, concise, and rapid development"
 		echo "of small Python-Flask projects. To construct a new project, run"
@@ -184,7 +205,7 @@ case "$1" in
 		echo
 		echo "For a getting started example, take a look at the README!"
 		echo "************************************************************************************"
-		echo
+		echo -e "\n"
 		;;
 
 	"banner")
@@ -202,39 +223,6 @@ case "$1" in
 		;;
 
 	*)
-		echo
-		echo "Usage: 
-		create [PROJECT_NAME],
-		create-view [PROJECT_NAME] [VIEW_NAME],
-		create-template [PROJECT_NAME] [TEMPLATE_NAME],
-		create-env [PROJECT_NAME],
-		del-env [PROJECT_NAME],
-		reset-env [PROJECT_NAME],
-		banner"
-		echo
+		usage
 		;;
 esac
-
-# destroy project taken out... can be wayyy too fatal
-# "destroy")
-	
-# 	if [[ -z "$2" ]]; then
-# 		echo "Usage: destroy [PROJECT_NAME]"
-# 		exit 1
-# 	fi
-
-# 	if ! [[ -d "$2" ]]; then
-# 		echo "Could not locate project $2"
-# 		exit 1
-# 	fi
-
-# 	if [[ -d "$2" ]]; then
-# 		echo "Destroying project $2..."
-# 		rm -rf "$2"
-# 		if [[ -d "$2" ]]; then
-# 			echo "Could not destroy project $2"
-# 			exit 1
-# 		fi
-# 		echo "Successfully destroyed project $2"
-# 	fi
-# 	;;
